name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@ccac87339fceef23738ec422e29850a70e9e6f46
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
